callcenter/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from django.conf.urls import include
from callcenter.views import CaseListView, ClientNewPhView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

#app_name = 'callcenter'


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'clients', views.ClientViewSet)
router.register(r'client-phones', views.ClientPhoneViewSet)
router.register(r'client-symptom-question-answer-list', views.ClientSymptomQuestionAnswerViewSet)
router.register(r'chatbotclient', views.ChatbotClientViewSet)




urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('clients/<int:id>/additional-ph', views.add_additional_ph, name='client_additional_phone'),
    path('clients/<int:id>/info/', views.first_contact, name='client_info'),
    path('clients/<int:id>/symptoms/', views.symptoms_confirmed_by_call, name='client_call_symptoms'),
    path('clients/<int:id>/refer/', views.refer_tb_client, name='refer_tb_client'),
    path('clients/<int:id>/social-platforms/', views.is_active_in_social_platforms, name='client_active_social_platforms'),
    path('state_regions/', views.get_state_regions),
    path('townships/<int:state_region_id>/', views.get_townships, name='get_townships'),
    path('channels/<int:township_id>/', views.get_channels, name='channels'),
    path('site_addresses/<int:state_region_id>/<int:township_id>/<int:channel_id>/', views.get_site_addresses, name='site_addresses'),
    path('clients/<int:id>/refer-locations/', views.refer_locations, name='client_ref_locations'),
    path('clients/<int:id>/reach-info/', views.reach_info, name='client_reach_info'),
    path('investigation_types/', views.get_investigation_types),
    path('investigation_results/<int:investigation_type_id>/', views.get_investigation_results),
    path('clients/<int:id>/taken-investigations/', views.taken_investigations, name='client_taken_investigations'),
    path('clients/<int:id>/tb-confirmation/', views.tb_confirmation, name='client_tb_confirmation'),
    path('tb_regimes/', views.get_tb_regimes),
    path('clients/<int:id>/tb-treatment/', views.tb_treatment, name='client_tb_treatment'),
    path('investigation-results', views.load_investigation_results, name='investigation_results'),
    path('townships/', views.load_townships, name='townships'),
    path('addresses/', views.load_addresses, name='addresses'),
    path('clinic/', views.load_clinic, name='clinic'),

    # path('channel/', views.load_channel, name='channel'),
    # path('organization/', views.load_organization, name='organization'),
    #path('sites/', views.load_available_sites, name='sites'),
    #path('test/', views.test, name='test'),
    path('testone/', views.testone, name='test'),
    path('create-client/', views.create_client, name='create-client'),
    path('test-co-pilot/', views.test_co_pilot, name='test-co-pilot'),
    path('new-tb-referral/', views.new_tb_referral, name='new-tb-referral'),
    path('test-api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('cases/', CaseListView.as_view(), name='case_list'),
    # path('login/', LoginView.as_view(), name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('clients/<int:id>/', login_required(views.client_details), name='client_details'),
    path('clients/<int:pk>/new-contact', views.client_stage1_new_contact, name='client_stage1_new_contact'),
    path('clients/<int:pk>/additional-contact', views.client_stage1_additional_contact, name='client_stage1_additional_contact'),
    path('clients/<int:pk>/new-ph', ClientNewPhView.as_view(), name='client_new_ph'),
    path('clients/<int:pk>/new-diagnosis', views.client_stage2_new_diagnosis, name='client_stage2_new_diagnosis'),
    path('clients/<int:pk>/new-investigation', views.client_stage2_new_investigation, name='client_stage2_new_investigation'),
    path('clients/<int:pk>/new-tb-register', views.client_stage3_new_tb_register, name='client_stage3_new_tb_register'),
    #path('test-api/client-question-answer-bulk-create-update/', views.ClientSymptomQuestionAnswerView.as_view(), name='client-question-answer-bulk-create-update'),
    #path('use-coupon/', views.UseCouponView.as_view(), name='coupon')
    #?coupon_code=COUPONTEST01
]

careconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('callcenter.urls')),
]

callcenter/models.py
from django.db import models
import uuid
from django.utils import timezone
#import datetime
# Create your models here.

CHANNEL_NAME_CHOICES = [('Public', 'Public'),('Private', 'Private')]


class BaseModel(models.Model):
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

#STAGE_CHOICE = [('1','Stage1ChatbotCompletion'),('2','Stage1Contact'),('3','Stage1TBReferral'),('4','')]
class Stage(BaseModel):
    description = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "01. Stages"
    def __str__(self):
        return f'{self.description}'

# class Case(BaseModel):
#     #case_id = models.BigAutoField(primary_key=True,editable=False)
#     #case_id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
#     #stage = models.CharField(max_length=1,choices=STAGE_CHOICE)
#     stage_id = models.ForeignKey(Stage,on_delete=models.PROTECT)

CLIENT_TYPE_CHOICE = [('Self','Self'),('Family','Family')]
GENDER_CHOICE = [('Male','Male'),('Female','Female'),('Other','Other')]
AGE_RANGE_CHOICE = [('BelowFifteen','BelowFifteen'),('FifteenAndAbove','FifteenAndAbove')]
class Client(BaseModel):
    type = models.CharField(max_length=255,null=False,choices=CLIENT_TYPE_CHOICE)
    gender = models.CharField(max_length=255,null=False,choices=GENDER_CHOICE)
    #gender = models.ForeignKey(Gender,on_delete=models.CASCADE)
    age_range = models.CharField(max_length=255,null=False,choices=AGE_RANGE_CHOICE)
    stage = models.ForeignKey(Stage,on_delete=models.PROTECT,default=1)

    def __str__(self):
        return f"{self.id} {self.type} {self.gender} {self.age_range}"

class ChatbotClient(BaseModel):
    social_media_id = models.CharField(max_length=255,null=False)
    social_media_name = models.CharField(max_length=255,null=False)
    client = models.ForeignKey(Client,on_delete=models.PROTECT,null=True)

class TBReferralClient(BaseModel):
    name = models.CharField(max_length=255,null=False)
    age_range = models.CharField(max_length=255,null=True,choices=AGE_RANGE_CHOICE)
    client = models.ForeignKey(Client,on_delete=models.PROTECT)

PHONE_TYPE_CHOICE = [('1','Primary'),('2','Additional')]
class ClientPhone(BaseModel):
    phone_number = models.CharField(max_length=255,null=False)
    phone_type = models.CharField(max_length=255,null=False,choices=PHONE_TYPE_CHOICE,default='1')
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    can_be_contacted = models.BooleanField(null=True,blank=True)

QUESTION_TYPE_CHOICE = [('c','Child'),('a','Adult')]
class SymptomQuestion(BaseModel):
    description = models.CharField(max_length=255,null=False)
    type = models.CharField(max_length=1,null=False,choices=QUESTION_TYPE_CHOICE)
    is_active = models.BooleanField()

    class Meta:
        verbose_name_plural = "02. Symptom questions"

    def __str__(self):
        return f"{self.id} {self.description}"

class ClientSymptomQuestionAnswer(BaseModel):
    question = models.ForeignKey(SymptomQuestion,on_delete=models.PROTECT)
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    answer = models.BooleanField()
    stage = models.ForeignKey(Stage,on_delete=models.PROTECT)

class ClientTBReferral(BaseModel):
    is_willing_to_be_referred = models.BooleanField()
    client = models.ForeignKey(Client,on_delete=models.PROTECT)

class CallAttempt(BaseModel):
    count = models.PositiveSmallIntegerField()
    current_attempt_date = models.DateField()
    next_attempt_date = models.DateField()
    stage = models.ForeignKey(Stage,on_delete=models.PROTECT)
    client =models.ForeignKey(Client,on_delete=models.PROTECT)

class SocialPlatform(BaseModel):
    name = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "03. Social platforms"

    def __str__(self):
        return f"{self.name}"

class ClientSocialPlatform(BaseModel):
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    social_platform = models.ForeignKey(SocialPlatform,on_delete=models.PROTECT)
    is_active = models.BooleanField()

class StateRegion(BaseModel):
    name = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "04. States regions"

    def __str__(self):
        return f"{self.name}"

class Township(BaseModel):
    name = models.CharField(max_length=255,null=False)
    name_mm = models.CharField(max_length=255,null=False,default="")
    state_region = models.ForeignKey(StateRegion,on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "05. Townships"

    def __str__(self):
        return f"{self.name}"

class Channel(BaseModel):
    name = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "06. Channels"

    def __str__(self):
        return f"{self.name}"

class Organization(BaseModel):
    name = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "07. Organizations"

    def __str__(self):
        return f"{self.name}"

SITE_TYPE_CHOICE = [('1','Referral'),('2','Register')]
class SiteLocation(BaseModel):
    is_active = models.BooleanField(null=False)
    state_region = models.ForeignKey(StateRegion,on_delete=models.PROTECT)
    township = models.ForeignKey(Township,on_delete=models.PROTECT)
    channel = models.ForeignKey(Channel,on_delete=models.PROTECT)
    organization = models.ForeignKey(Organization,on_delete=models.PROTECT)
    clinic_name = models.CharField(max_length=255,null=True,blank=True)
    clinic_name_mm = models.CharField(max_length=255,null=True,blank=True)
    site_address = models.CharField(max_length=255,null=False)
    site_address_mm = models.CharField(max_length=255,null=True)
    provider_name = models.CharField(max_length=255,null=True)
    provider_name_mm = models.CharField(max_length=255,null=True)
    site_type = models.CharField(max_length=255,null=False,choices=SITE_TYPE_CHOICE)


    class Meta:
        verbose_name_plural = "08. SiteLocations"

    def __str__(self):
        return f"{self.clinic_name} {self.clinic_name_mm} {self.site_address} {self.site_address_mm} {self.site_type} {self.organization_id} {self.channel_id} {self.township_id} {self.state_region_id}"
# class RegisterSiteLocation(BaseModel):
#     is_active = models.BooleanField(null=False)
#     state_region_id = models.ForeignKey(StateRegion,on_delete=models.PROTECT)
#     township_id = models.ForeignKey(Township,on_delete=models.PROTECT)
#     channel_id = models.ForeignKey(Channel,on_delete=models.PROTECT)
#     organization_id = models.ForeignKey(Organization,on_delete=models.PROTECT)
#     site_name = models.CharField(max_length=255,null=False)

ACTION_TYPE_CHOICE = [('1','Referral'),('2','Register')]
class ClientRefRegLocation(BaseModel):
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    site_location = models.ForeignKey(SiteLocation,on_delete=models.PROTECT)
    action_date = models.DateField()
    action_type = models.CharField(max_length=1,null=False,choices=ACTION_TYPE_CHOICE)

class ClientReachInfo(BaseModel):
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    is_reached_to_referral_site = models.BooleanField(null=False)
    reached_date = models.DateField(null=False)
#    referred_location = models.ForeignKey(ClientRefRegLocation,on_delete=models.PROTECT)

class InvestigationType(BaseModel):
    type_description = models.CharField(max_length=255,null=False)

    class Meta:
        verbose_name_plural = "09. InvestigationTypes"

    def __str__(self):
        return f"{self.type_description}"


RESULT_TYPE_CHOICE = [('Positive','Positive'),('Negative','Negative')]
class InvestigationResult(BaseModel):
    result_description = models.CharField(max_length=255,null=False)
    result_type = models.CharField(max_length=255,null=False,choices=RESULT_TYPE_CHOICE,default="")
    investigation_type = models.ForeignKey(InvestigationType,on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "10. InvestigationResults"

    def __str__(self):
        return f"{self.result_description}"

class ClientInvestigatedResult(BaseModel):
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    taken_investigation_type = models.ForeignKey(InvestigationType,on_delete=models.PROTECT)
    taken_investigation_result = models.ForeignKey(InvestigationResult,on_delete=models.PROTECT)
    taken_investigation_date = models.DateField(null=False)

    class Meta:
        ordering = ['-taken_investigation_date']

TB_DIAGNOSIS_CHOICE = [('Positive','Positive'),('Negative','Negative')]
class ClientTBConfirmation(BaseModel):
    is_bat_confirmed = models.BooleanField(null=False)
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    tb_diagnosis = models.CharField(max_length=8,choices=TB_DIAGNOSIS_CHOICE)
    diagnosis_date = models.DateField(null=False)

class TxRegime(BaseModel):
    type = models.CharField(max_length=255,null=False)
    is_active = models.BooleanField(null=True)

    def __str__(self):
        return f'{self.type}'

    class Meta:
        verbose_name_plural = "11. TxRegimes"

class ClientTBTreatment(BaseModel):
    client = models.ForeignKey(Client,on_delete=models.PROTECT)
    is_registered_for_tx = models.BooleanField()
    is_same_as_referred_site = models.BooleanField(null=True)
    # tx_regime = models.CharField(max_length=255,null=False)
    tx_regime = models.ForeignKey(TxRegime,on_delete=models.PROTECT)
    registered_date = models.DateField(null=False,default=timezone.now)

callcenter/templates/callcenter/add_reach_info_modal_form.html
<!-- Modal -->
<div class="modal fade" id="reachInfoModal" tabindex="-1" aria-labelledby="reachInfoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reachInfoModalLabel">Reach Info</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div id="reachInfoFormErrorMessage" class="alert alert-danger d-none"></div>
        <form id="reachInfoForm" class="row g-3" data-client-id={{ client.id }}>
          <div class="mb-3">
            <label for="id_is_reach" class="form-label">Is reached to Referral Site?</label>
            <select id="id_is_reach" class="form-select" name="is_reach">
                <option value="" selected>Select Answer</option>
                <option value="True">Yes</option>
                <option value="False">No</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="id_reached_date" class="form-label">Reached Date</label>
            <input type="date" id="id_reached_date" class="form-control" name="reached_date" required>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitReachInfo">Submit</button>
      </div>
    </div>
  </div>
</div>

callcenter/templates/callcenter/add_social_platform_modal_form.html
<!-- Modal -->
<div class="modal fade" id="socialPlatformModal" tabindex="-1" aria-labelledby="socialPlatformModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="socialPlatformModalLabel">Social Platforms</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div id="socialPlatformFormErrorMessage" class="alert alert-danger d-none"></div>
        <form class="row g-3" id="socialPlatformForm" data-client-id={{ client.id }}>
          
          <div class="mb-3">
            <label for="platform1" class="form-label">Viber</label>
            <select name="platform1" class="form-select" required id="id_platform1">
              <option value="" selected>Select Answer</option>
              <option value="True">Yes</option>
              <option value="False">No</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="platform2" class="form-label">Telegram</label>
            <select name="platform2" class="form-select" required id="id_platform2">
              <option value="" selected>Select Answer</option>
              <option value="True">Yes</option>
              <option value="False">No</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="platform3" class="form-label">Whatsapp</label>
            <select name="platform3" class="form-select" required id="id_platform3">
              <option value="" selected>Select Answer</option>
              <option value="True">Yes</option>
              <option value="False">No</option>
            </select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitSocialPlatform">Submit</button>
      </div>
    </div>
  </div>
</div>

callcenter/templates/callcenter/add_symptoms_by_call.html
<!-- Modal -->
<div class="modal fade" id="symptomsModal" tabindex="-1" aria-labelledby="symptomsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="symptomsModalLabel">Symptoms confirmed by call</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div id="symptomsByCallFormErrorMessage" class="alert alert-danger d-none"></div>
          <form class="row g-3" id="symptomsByCallForm" data-client-id="{{ client.id }}">
              <!-- Form goes here -->
              
          </form>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitSymptomsByCall">Submit</button>
      </div>
    </div>
  </div>
</div>

callcenter/templates/callcenter/add_taken_investigation_modal_form.html
<!-- Modal -->
<div class="modal fade" id="takenInvestigationModal" tabindex="-1" aria-labelledby="takenInvestigationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="takenInvestigationModalLabel">Taken Investigation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div id="takenInvestigationFormErrorMessage" class="alert alert-danger d-none"></div>
        <form id="takenInvestigationForm" class="row g-3" data-client-id={{ client.id }}>
          <div class="mb-3">
            <label for="investigation-type-select" class="form-label">Investigation Type</label>
            <select id="investigation-type-select" class="form-select" name="investigation_type">
              <!-- Options will be populated dynamically -->
            </select>
          </div>
          <div class="mb-3">
            <label for="investigation-result-select" class="form-label">Investigation Result</label>
            <select id="investigation-result-select" class="form-select" name="investigation_result">
              <!-- Options will be populated dynamically -->
            </select>
          </div>
          <div class="mb-3">
            <label for="id_investigation_date" class="form-label">Investigation Date</label>
            <input type="date" id="id_investigation_date" class="form-control" name="investigation_date" required>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitTakenInvestigation">Submit</button>
      </div>
    </div>
  </div>
</div>

callcenter/templates/callcenter/add_tb_confirmation_modal_form.html
<!-- Modal -->
<div class="modal fade" id="tbConfirmationModal" tabindex="-1" aria-labelledby="tbConfirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tbConfirmationModalLabel">TB Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div id="tbConfirmationFormErrorMessage" class="alert alert-danger d-none"></div>
        <form id="tbConfirmationForm" class="row g-3" data-client-id={{ client.id }}>
          <div class="mb-3">
            <label for="id_tb_diagnosis" class="form-label">TB Diagnosis</label>
            <select id="id_tb_diagnosis" class="form-select" name="tb_diagnosis">
                <option value="" selected>Select Answer</option>
                <option value="Positive">Positive</option>
                <option value="Negative">Negative</option>
            </select>
          </div>
          <!--<div class="mb-3">-->
          <!--  <label for="id_diagnosis_date" class="form-label">Diagnosis Date</label>-->
          <!--  <input type="date" id="id_diagnosis_date" class="form-control" name="diagnosis_date" required>-->
          <!--</div>-->
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="submitTbConfirmation">Submit</button>
      </div>
    </div>
  </div>
</div>

callcenter/templates/callcenter/client_reach_info.html
{% extends 'main.html' %}

{% block content %}
{{ form.media }}

  <div class="container mt-5">
    <form method="POST" class="row g-3">
      {% csrf_token %}
      <h1>Reach Info</h1>
      {% if form.errors%}
      {% for field, errors in form.errors.items %}
      {% for error in errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{error}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endfor %}
      {% endif %}

      <div class="col-md-6">
        <label for="{{form.is_reach.id_for_label}}">{{ form.is_reach.label }}</label>
        {{ form.is_reach }}
      </div>
      <div class="col-md-6">
        <label for="{{form.reached_date.id_for_label}}">{{ form.reached_date.label }}</label>
        {{ form.reached_date }}
      </div>

      <div class="col-12">
        {{ form.hidden_client_id }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>




{% endblock %}

callcenter/templates/callcenter/client_success.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="alert alert-success" role="alert">
      Your message has been sent successfully. We will get back to you soon.
    </div>
  </div>
{% endblock %}

callcenter/templates/callcenter/client_taken_investigations.html
{% extends 'main.html' %}

{% block content %}
{{ form.media }}

  <div class="container mt-5">
    <form method="POST" class="row g-3">
      {% csrf_token %}
      <h1>Taken Investigations</h1>
      {% if form.errors%}
      {% for field, errors in form.errors.items %}
      {% for error in errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{error}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endfor %}
      {% endif %}

      <div class="col-md-6">
        <label for="{{form.investigation_type.id_for_label}}">{{ form.investigation_type.label }}</label>
        {{ form.investigation_type }}
      </div>
      <div class="col-md-6">
        <label for="{{form.investigation_result.id_for_label}}">{{ form.investigation_result.label }}</label>
        {{ form.investigation_result }}
      </div>
      <div class="col-md-6">
        <label for="{{form.investigation_date.id_for_label}}">{{ form.investigation_date.label }}</label>
        {{ form.investigation_date }}
      </div>

      <div class="col-12">
        {{ form.hidden_client_id }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>



<script>
$(document).ready(function() {

  var investigationTypeSelect = $('#investigation-type-select');
  var investigationResultSelect = $('#investigation-result-select');

  var investigationTypeId;


  investigationTypeSelect.on('change', function() {
    investigationTypeId = this.value;
    var xhr = new XMLHttpRequest();
    var url = "{% url 'investigation_results' %}?investigation_type_id=" + investigationTypeId;
    xhr.open('GET', url, true);
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        var investigations = JSON.parse(xhr.responseText);
        investigationResultSelect.html('<option value="">---------</option>');
        for (var i = 0; i < investigations.length; i++) {
          investigationResultSelect.append('<option value="' + investigations[i].id + '">' + investigations[i].result_description + '</option>');
        }
      } else {
        console.log(xhr.readyState + ' ' + xhr.status + ' error');
      }
    };
    xhr.send();
  });



});
</script>



{% endblock %}